### ISSUE TITLE
opt.params() missing even when library(HMMoce) is loaded - run_albacore.R

### ISSUE THREAD

**Issue by marosteg** [camrinbraun/HMMoce_run#1]
In run_albacore.R, the function opt.params() was supposedly missing even though the most recent dev version of HMMoce had been downloaded and then loaded via library(). Fix is achieved with
```
HMMoce:::opt.params()
```

**Comment by camrinbraun** [comment]
should be exported and thus fixed with https://github.com/camrinbraun/HMMoce/commit/c96dde95fe6d50ccbb0cb958a933ad96e959f9b3
